Octo.Net/Octo.Net.UI/Controllers/JoinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Octo.Net.BL;

namespace Octo.Net.UI.Controllers
{
    public class JoinController : Controller
    {
        // GET: Join
        public ActionResult Index()
        {
            Net.Models.User user = new Net.Models.User();
            return View(user);
        }

        [HttpPost]
        public ActionResult Index(Net.Models.User user, Net.Models.File file)
        {
            try
            {
                BL.User bluser = new BL.User();
                bluser.Insert(user, file);
                return RedirectToAction("Index");
            }
            catch 
            {
                return View(user);   
            }
        }

        // GET: User/Create
        public ActionResult Create()
        {
            Octo.Net.Models.User user = new Octo.Net.Models.User();
            return View(user);
        }

        // POST: BL.User/Create
        [HttpPost]
        public ActionResult Create(Octo.Net.Models.User user, Net.Models.File file, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        file = new Net.Models.File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = Net.Models.FileType.Avatar,
                            ContentType = upload.ContentType
                        };
                        using(var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            file.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        user.Files = new List<Net.Models.File> { file };
                    }
                    User blUser = new User();
                    blUser.Insert(user, file);
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
            return View();
        }

    }
}

Octo.Net/Octo.Net.UI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Octo.Net.UI.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login(string returnUrl)
        {
            ViewBag.Message = "Login";
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(Net.Models.User user, string returnurl)
        {
            ViewResult result = View(user);
            try
            {
                ViewBag.ReturnUrl = returnurl;
                BL.User blUser = new BL.User();

                //ViewBag.ReturnUrl = returnUrl;
                if (blUser.Login(user.UserName, user.Password))
                {
                    BL.User useree = new BL.User();
                    user = useree.LoadByUsername(user.UserName);

                    HttpContext.Session["user"] = user;
                    //return result;
                    if (!string.IsNullOrEmpty(returnurl))
                    {
                        return Redirect(returnurl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Profile");
                    }
                }
                ViewBag.Message = "Login Failed";

                return result;
            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View(user);
            }
        }

        public ActionResult Logout()
        {
            //Logged out
            HttpContext.Session["user"] = null;
            return RedirectToAction("Login", "Login");
        }

    }
}

Octo.Net/Octo.Net.UI/Views/Login/Login.cshtml
@model Octo.Net.Models.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="container">

    <div class="row pt-5">
        <div class="col-md-6">
            <h2>Login</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <form>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2", @type = "password" })
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Login" class="btn btn-primary btn-lg" />
                        </div>
                    </div>
                    <div class="col-md-offset-2 col-md-10">
                        <small>Not a member yet?  @Html.ActionLink(" Join Us! ", "Index", "Join") </small>
                    </div>

                </form>



                <div class="col-md-offset-2 col-md-10">
                    <a>Having trouble login in?</a>
                </div>
             }
        </div>
        <div class="col-md-6">
                <h3>Not a Member Yet?</h3>
                <ul>
                    <p>
                        We are so excited you decided to join our community.
                        We just need a little bit of information to get you started.
                    </p>
                    <p>
                        Meet other artists, find inspiration, and help promote and encourage creativity.
                        Create and share your portfolio, collaborate with fellow artists hone your skills together.
                    </p>
                </ul>
                @Html.ActionLink(" Join Us! ", "Index", "Join",null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>

Octo.Net/Octo.Net.UI/Views/Login/Logout.cshtml
@{
    ViewBag.Title = "Logout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>You are logged out.</h2>